version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
      - "5555:5555"  # Prisma Studio
    environment:
      - NODE_ENV=development
      - PORT=5001
    env_file:
      - ./backend/.env.develop
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend/prisma:/app/prisma

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./backend/db.env 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  pgdata: